### ISSUE TITLE
import Vcard from FFOS 3.0, error names

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-contacts#95] opened 2015-05-31 10:12 UTC
Hello,

When I imported the vcards I had from the export of FFOS 3.0, first and last name were not field. The first and last name were together inside the "other name" field.
I send the two vcard to Frank (I can't put them public :-), the one from FFOS and the one from cozy, after importing the FFOS's one.

I guess that was the reason of a problem with my sync problem with the FFOS apps.
Cheers,
Thatoo

**Comment by clochix** [comment] 2015-06-16 12:42
@frankrousseau did you had time to have a look at this one ?

**Comment by frankrousseau** [comment] 2015-06-16 13:23
Not yet. It's still on my Todo List.

**Comment by frankrousseau** [comment] 2015-07-01 22:03
It should be fixed. @Thatoo could you try to uninstall / install Cozy Contacts and tell us if it's working now.

**Comment by frankrousseau** [comment] 2015-07-01 22:03
I only worked on the import case, not the sync case.

**Comment by Thatoo** [comment] 2015-07-08 21:30
no, it doesn't work.
I deleted the data, uninstall and reinstall cozy-contact. I import the vcard that I previously exported from FFOS and the same, first name and last name are combined in "Autres prénoms".
Do you want I send you my new FFOS vcard file?

**Comment by jsilvestre** [comment] 2015-07-10 11:33
@aenario correct me if I'm wrong but this is somewhat an expected behaviour when vcf is ont well formed. There are two fields to handle names ans one of them forces us to put evrything in a single field because we can't guess whatnis first name, middle name or last name (or other). Could it ne thar by any chance? @frankrousseau

**Comment by frankrousseau** [comment] 2015-07-11 12:02
The problem is that FFOS doesn't build the name field like other platforms. I don't understand why it doesn't work. I will check for the build, because now it's properly handled by `cozy-vcard`:

https://github.com/cozy/cozy-vcard/blob/master/test/index.coffee#L278-L285

https://github.com/cozy/cozy-vcard/blob/master/test/ffos.vcf

**Comment by aenario** [comment] 2015-07-15 10:06
cozy-contacts's master is not built. I just pushed the development branch as master, which include a build, could you please try again ?

**Comment by Thatoo** [comment] 2015-07-17 08:34
I'd like to but Data Browser is not working, I can't delete my contacts... last time already, I had to delete them one by one because there were no button to delete them all...

**Comment by Thatoo** [comment] 2015-07-17 08:45
Done!
still the same problem.

**Comment by frankrousseau** [comment] 2015-07-17 17:10
Sorry @Thatoo. I don't know how to solve that one.

**Comment by Thatoo** [comment] 2015-07-17 17:21
I guess it's ok for now, not many people are going to do it.
For me, all my contact are in Thunderbird so I'll import from that. The most important for me now, will be the sync :-)

**Comment by jsilvestre** [comment] 2016-08-11 14:20
Unfortunately, Firefox OS looks like a dead project, so we close it :(

**Closed by jsilvestre** 2016-08-11 14:20 UTC
Labels: 0 - Idea box, bug

**Comment by Thatoo** [comment] 2016-08-31 05:23
no, B2G OS is the name of the code project. It's not dead.
The commercial project has changed. That's it.
