### ISSUE TITLE
VCF with DOS line ending does not work

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-contacts#225] opened 2016-01-21 19:38 UTC
Having a VCF file with windows/dos format (^M at eol) are rejected as "not a VCF" file by contacts.
Simply removing ^M works

**Comment by clochix** [comment] 2016-01-22 16:02
Thanks for reporting @dkm,
I close this one as it's a duplicate of #180. The bug has been fixed, and I hope the fix will be published soon.

**Closed by clochix** 2016-01-22 16:02 UTC
