### ISSUE TITLE
Truncate long email addresses

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#219] opened 2016-01-21 10:35 UTC
Long emails addresses (such as github automate sender) broken rendered layout. We need to truncate them and find a way to view them full, copy, etc (tooltip, action button, whatever). ~~@kelukelu any thoughts about it?~~

Ok, so we just force wrapping in multiple lines :+1:

**Comment by poupotte** [comment] 2016-01-26 17:02
I close this issue it's a duplicate of https://github.com/cozy/cozy-contacts/issues/158

**Closed by poupotte** 2016-01-26 17:02 UTC
Labels: 1 - Backlog, bug, duplicate
