### ISSUE TITLE
Contacts Application is not authorized (docType:user)

### ISSUE THREAD

**Issue by obigroup** [cozy/cozy-contacts#87] opened 2015-04-21 14:30 UTC
When I start contacts app, it logs this on data-system.log : 
```
[2015-04-21 14:19:28:157] error - app:error | contacts Application is not authorized
[2015-04-21 14:19:28:159] error - app:error | Error: contacts Application is not authorized
    at /usr/local/cozy/apps/data-system/build/server/helpers/utils.js:38:13
    at /usr/local/cozy/apps/data-system/build/server/lib/token.js:61:22
    at checkToken (/usr/local/cozy/apps/data-system/build/server/lib/token.js:26:14)
    at module.exports.checkDocType (/usr/local/cozy/apps/data-system/build/server/lib/token.js:37:12)
    at module.exports.checkPermissions (/usr/local/cozy/apps/data-system/build/server/helpers/utils.js:30:10)
    at Object.module.exports.checkPermissionsByType [as handle] (/usr/local/cozy/apps/data-system/build/server/middlewares/utils.js:61:10)
    at next_layer (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/route.js:107:5)
    at /usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/index.js:213:24
    at param (/usr/local/cozy/apps/data-system/node_modules/americano/node_modules/express/lib/router/index.js:303:14)
```
If you try to log docType in /usr/local/cozy/apps/data-system/build/server/lib/token.js you will see that app try to use docType: user but can't found this docType on app permissions.

Do you know why ?

Thanks.

**Comment by aenario** [comment] 2015-04-21 14:35
Hi @obigroup, this is caused by cozydb (ref = https://github.com/cozy/cozy-db/issues/9). At startup, the app will try to create the user/all view even if it doesnt use it. This will not cause any bug but will display an error in the data-system log. 

It needs to be fixed in cozy-db.

**Comment by aenario** [comment] 2015-04-21 14:36
I am closing this issue, please subscribe to https://github.com/cozy/cozy-db/issues/9

**Closed by aenario** 2015-04-21 14:37 UTC
