### ISSUE TITLE
Export doesn't work

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-contacts#199] opened 2016-01-02 16:53 UTC
v2.1.3

After selecting one or several contacts, the "Export" button shows up, but clicking on it doesn't do anything.

This faulty behavior is the same for the Export button located in the "Setup" dialog.

**Comment by clochix** [comment] 2016-01-05 15:57
Hi @f6fvy,
Thanks for reporting. Do you see any error inside your browser console, or in server logs?

**Comment by f6fvy** [comment] 2016-01-05 16:11
1/ Correction : It doesn't work with "SELECT ALL" contacts checked (or the export button in the settings dialog). If I manually select several contacts, it works...

2/ I get this trace error in the console :+1: 

---

TypeError: a.join is not a function "https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js" 9 43 TypeError: a.join is not a function
Trace de la pile :
h@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:9:43
u.toVCF@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:8:29516
o</e.prototype.toVCF/<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:2:14846
o</e.prototype.picturetoa@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:2:14735
o</e.prototype.toVCF@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:2:14799
v.invoke/<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:3:24846
v.collect@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:3:23929
v.invoke@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:3:24794
v.mixin/</v.prototype[e]@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:4883
o</r.prototype.bulkExport@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:3:18435
o</r.prototype.viewEvents["bulk:export"]@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:3:16696
v@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:9292
y@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:9101
f@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:7020
l.trigger@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:8994
o._triggerMethod</<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:5:18556
o.View<.triggerMethod@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:5:31945
o.View<._buildViewTrigger/<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:5:31747
Q.event.dispatch@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:2:15757
Q.event.add/m.handle@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:2:12567
 h@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:9:43
u.toVCF@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:8:29516
o</e.prototype.toVCF/<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:2:14846
o</e.prototype.picturetoa@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:2:14735
o</e.prototype.toVCF@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:2:14799
v.invoke/<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:3:24846
v.collect@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:3:23929
v.invoke@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:3:24794
v.mixin/</v.prototype[e]@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:4883
o</r.prototype.bulkExport@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:3:18435
o</r.prototype.viewEvents["bulk:export"]@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/app.js:3:16696
v@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:9292
y@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:9101
f@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:7020
l.trigger@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:4:8994
o._triggerMethod</<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:5:18556
o.View<.triggerMethod@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:5:31945
o.View<._buildViewTrigger/<@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:5:31747
Q.event.dispatch@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:2:15757
Q.event.add/m.handle@https://laurenthaas.cozycloud.cc/apps/contacts/scripts/vendor.js:2:12567
 app.js:1:8284

TypeError: a.join is not a function
 vendor.js:9:43

---

Hope it helps !

**Comment by clochix** [comment] 2016-01-05 16:25
Thanks, @f6fvy, 
It's seems to be the same error [also reported on the forum](https://forum.cozy.io/t/contacts-export-de-plusieurs-contacts-non-fonctionnel/1793/3).

Probably in [function exportAdr](https://github.com/cozy/cozy-contacts/blob/master/client/vendor/cozy-vcard-0.2.14.js#L807) called in `VCardParser.toVCF`.

**Comment by clochix** [comment] 2016-01-05 16:33
@frankrousseau I reproduced the issue and can confirm it's because we call `exportAdr` whith `options.value` as a string, while an array is expected.
It has [already been fixed](https://github.com/cozy/cozy-vcard/commit/a2d683efd18031073a1f1b6a46053a99e3bf153e) in `Cozy-vcard`, so we just need to update the dependency to the latest version of CozyVcard

**Comment by f6fvy** [comment] 2016-01-05 16:36
Thanks for your great support.

**Comment by frankrousseau** [comment] 2016-01-05 17:10
Great thank you @clochix. I make a PR tonight for this.

**Comment by f6fvy** [comment] 2016-01-13 13:28
Ticket update

With version v2.1.4, the export file is now created, *but* there are no phone numbers (at all) in it ! Same issue with individual (or grouped) selection.

So, for now, the export is still not usable :-(

**Comment by clochix** [comment] 2016-01-15 16:06
Seems like another problem with cozy-vcard. I just [fixed a typo in the lib](https://github.com/clochix/cozy-vcard/commit/747efc51c86cdd949765d66b4ebe9c210c194dea), @m4dz would you mind applying this fix by hand on your working directory and see if it fixes the export of tel, address, email and url?

**Comment by frankrousseau** [comment] 2016-01-15 16:42
This issue depends on the context. On my Cozy it works well. Maybe that some fields lead to an error. @f6fvy Do you know if your contacts have something special?

**Comment by f6fvy** [comment] 2016-01-15 16:56
Most of them don't have address or email if it matters. The phone numbers are using the fields named Cell or Voice or Home. They are displayed in the app without any problem.

But even with one contact selected only, I never get a phone number in the export. Rather strange.

**Comment by clochix** [comment] 2016-01-18 09:31
I can confirm, I have the save behavior as @f6fvy, and having a look at our vcard library, I found a typo in the code that may affect export of some fields.

**Comment by m4dz** [comment] 2016-01-19 10:05
@clochix cozy-vcard 0.2.17 is now on the development branch. Can you make a try and tell me if it's solved?

**Comment by poupotte** [comment] 2016-01-22 17:02
This issue should be fixed in the next version :) .

**Closed** 2016-01-25 11:55 UTC
Labels: 6 - To publish, bug

**Comment by poupotte** [comment] 2016-01-25 12:21
This issue is fixed in new release : v2.1.5

**Comment by f6fvy** [comment] 2016-01-25 14:07
Yippee ! It's working now ! Thanks @clochix @poupotte @frankrousseau @m4dz et al. !
